### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by RichardTHF** [Dreamacro/clash-tracing#16]
Hi, 

Having an issue where I am missing data in my Clash-Tracing Dashboard. 

![image](https://user-images.githubusercontent.com/5789676/148731395-ec2bcad6-fa95-4ce3-90d1-bdc2b38f58d5.png)

It feels like InfluxDB is only logging traffic, as when I try and add any other kind of data source the only thing found is traffic. 

![image](https://user-images.githubusercontent.com/5789676/148731472-85c60090-8d29-4868-8ffc-17eb116c19dc.png)

I am using Luci-Clash-App and Clash Premium 2022.01.03 and have added the tracing stuff to my config? any suggestions? 

```profile:
  # open tracing exporter API
  tracing: true
```

**Comment by Dreamacro** [comment]
what's your clash version and can you provide a more detailed configuration?

**Comment by RichardTHF** [comment]
Thanks for the response

I am using Clash Premium 2022.01.03 which I believe is built with Clash 1.9.0. 

```
# HTTP 代理端口
port: 7890
# SOCKS5 代理端口
socks-port: 7891
# Linux 和 macOS 的 redir 代理端口
redir-port: 7892
# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info
# Clash 的 RESTful API
external-controller: '0.0.0.0:9090'

# RESTful API 的口令
secret: '123456'

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
 external-ui: folder

 # open tracing exporter API
profile: 
  tracing: true
```

Is this enough of the config? if you mean as in how do I have it setup I am running frainzy1477's luci-app-clash (https://github.com/frainzy1477/luci-app-clash) on OpenWRT.
