### ISSUE TITLE
基于Vector/Loki的最新版有关问题

### ISSUE THREAD

**Issue by OUZYcn** [Dreamacro/clash-tracing#19]
作为半桶水用户，有几个问题希望交流一下。 

1. 这个tracing的配置指导真的不是吃瓜用户 friendly

- 当前所有配置及操作， 默认考虑的Linux用户是root用户进行操作，且该Host中没有任何container的情况，例如Grafana、Portainer。
- 因为Vector的默认端口，或者是vector.toml配置文件中端口配置就是9000，这个与Portainer默认端口冲突。 

2. 目录访问权限问题

- Loki与Grafana的container内部启动用户ID，绝大概率与Host bind 目录的用户ID不一致，因此没有会造成无法写入。 
- 所以，要么得通过id -u的结果，作为对应container的启动用户。 

3. Grafana dashboard的配置

- 其实，即便加入loki的data source，dashboard中的各项配置，貌似不能简单的修改data source这么简单，因为只是修改datasource不能查询出结果。。。实际上是有数据的。 
- 至少相对熟悉influxdb的情况，暂时还没搞懂Loki的数据查询方式，“Query inspector”中查不到结果。。。

**最后，可否出个相对详细的How-to呢？**
@Dreamacro 

```
version: '3'
services:
  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    user: '1100'
    ports:
      - "3100:3100" ##将loki的端口暴露出来，可以用现有的Grafana访问
    volumes:
      - ./loki/data:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml
#  grafana:
#    image: grafana/grafana-oss:latest
#    user: '0'
#    volumes:
#      - ./grafana:/var/lib/grafana
#    ports:
#      - "3001:3000"
#    container_name: grafana_OSS
  vector:
    image: timberio/vector:0.X-alpine
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml
    container_name: vector
    depends_on:
      - loki
  reporter:
    build: .
    environment:
      CLASH_HOST: '192.168.1.250:9090'
      CLASH_TOKEN: '123456'
      VECTOR_ADDR: 'vector:9001' ##对应vector.toml配置端口
    container_name: reporter
    depends_on:
      - vector
```

**vector.toml**

```
[sources.mixed]
type = "socket"
address = "0.0.0.0:9001" ##我自己修改了端口
mode = "tcp"
decoding.codec = "json"
host_key = ""

[transforms.traffic-input]
type = "filter"
inputs = [ "mixed" ]
condition = "exists(.up)"

[transforms.tracing-input]
type = "filter"
inputs = [ "mixed" ]
condition = "!exists(.up)"

[transforms.traffic]
type = "remap"
inputs = [ "traffic-input" ]
source = """
.type = "traffic"
del(.source_type)"""

[transforms.tracing]
type = "remap"
inputs = [ "tracing-input" ]
source = """
.type = downcase!(.type)
del(.source_type)
if exists(.metadata) {
    .metadata_dstip = .metadata.destinationIP
    .metadata_dstport = .metadata.destinationPort
    .metadata_host = .metadata.host
    .metadata_network = .metadata.network
    .metadata_srcip = .metadata.sourceIP
    .metadata_srcport = .metadata.sourcePort
    .metadata_type = .metadata.type
    .metadata_dnsmode = .metadata.dnsMode
    del(.metadata)
}
"""

[sinks.loki]
type = "loki"
inputs = [ "traffic", "tracing" ]
endpoint = "http://192.168.1.5:3100"
encoding.codec = "json"
labels.type = "{{ type }}"

```
