### ISSUE TITLE
No Data?

### ISSUE THREAD

**Issue by xx10n31y** [Dreamacro/clash-tracing#27]
- 内核文件
```bash
http --download https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.04.17.gz
```

- clash config.yaml
```yaml
mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 172.17.0.1:9090 # docker
#secret: ""
profile:
  tracing: true
```

克隆本项目后修改`.env`文件中的`CLASH_HOST`为`172.17.0.1:9090`, 创建`grafana`文件夹并给777权限后执行`docker-compose up -d`

### 遇到的问题
- 添加数据源,设置成`http://loki:3100`会提示502错误码, 修改docker-compose.yaml暴露端口才可以
- 两个panels没有数据
![image](https://user-images.githubusercontent.com/57975788/168541228-21631f23-8a78-4cb1-98b3-fbdbac78226b.png)
![image](https://user-images.githubusercontent.com/57975788/168541257-1e607624-cf75-41f4-a3df-96264b07a57b.png)

**Comment by Dreamacro** [comment]
172 是 docker 网卡的？不建议绑在 docker 网卡，可以绑在出口网卡的 ip 上

**Comment by xx10n31y** [comment]
> 172 是 docker 网卡的？不建议绑在 docker 网卡，可以绑在出口网卡的 ip 上

是docker的网卡的, 我试过绑在出口网卡上(路由器自动分配的IP), 好像也是没有数据, 不知道是不是还要做别的配置?

**Comment by Dreamacro** [comment]
是什么系统？Linux 吗？进容器 curl 一下呢

**Comment by xx10n31y** [comment]
> 是什么系统？Linux 吗？进容器 curl 一下呢

上星期刚安装的arch Linux, 环境相对来说比较干净的.

然后进入到 `grafana` 和 `vector` 安装curl后, `curl http://loki:3100 -vvv`, 得到以下结果
![image](https://user-images.githubusercontent.com/57975788/168578320-5c316be1-095f-4dd3-b33c-834576d0d0d5.png)

**Comment by Dreamacro** [comment]
502 好像是权限问题吧，你看一下 loki 容器的日志

**Comment by xx10n31y** [comment]
> clash 的 tracing 配置打开了吗

打开了的

```yaml
mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 192.168.2.218:9090
#secret: ""
profile:
  tracing: true
```
